locale = "en-AU"
label = "English (Australia)"
direction = "ltr"
weight = 1

title = "Michael Francis David"
copyright = "&copy; 2026 Michael Francis David"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Michael Francis David"
  image = "img/Avatar.jpg"
  headline = "Mathematics and Computer science student"
  bio = "I'm a first-year Mathematics and Computer Science Student at RUDN University, focusing on cybersecurity. My interests include operating systems, networking, and security research."
  links = [
    { github = "https://github.com/Ushie47" },
  ]
